# Generated by Django 4.2.4 on 2023-08-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField()),
                ('date', models.DateField()),
                ('overtime_increment', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DeductionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('sur_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reporting_time', models.TimeField()),
                ('leaving_time', models.TimeField()),
                ('front_image', models.ImageField(upload_to='employee_images/')),
                ('right_image', models.ImageField(upload_to='employee_images/')),
                ('left_image', models.ImageField(upload_to='employee_images/')),
                ('fingerprint', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confirmed', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.employee')),
                ('overtime_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.deductionreason')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmed', models.BooleanField()),
                ('deduction_timestamp', models.DateTimeField()),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.attendancerecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.employee')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.deductionreason')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_timestamp', models.DateTimeField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.adminuser')),
                ('overtime_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.overtime')),
            ],
        ),
        migrations.AddField(
            model_name='deductionreason',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.employee'),
        ),
        migrations.CreateModel(
            name='DeductionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_timestamp', models.DateTimeField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.adminuser')),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.salarydeduction')),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.employee'),
        ),
    ]
