# Generated by Django 4.2.4 on 2023-08-30 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImperialEmployeesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='late_decrement',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overtime',
            name='overtime_minutes',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.departments'),
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ImperialEmployeesApp.position'),
        ),
    ]
