# Generated by Django 4.2.4 on 2023-08-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImperialEmployeesApp', '0002_departments_position_remove_employee_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
